### ISSUE TITLE
学習データのoversampling

### ISSUE THREAD

**Issue by mitsu-h** [mitsu-h/BirdCLEF#17]
クラス不均衡なデータとなっているのが学習が上手くいかない原因としてあるので、oversamplingを実装する

**Comment by kenken118** [comment]
pytorchのdataloaderのまま実装する（imbalanced dataset sampler）の実装が難しければ、inbalanced-learnのSMOTEモジュールを使うのが一般的みたいです。
（一回train_test_splitでデータ分割する必要がありますが...）

下記のcolab notebookを参考に、Standardscalerでの処理の部分をSMOTEに置き換えてみるのはどうですかね？
colab：https://colab.research.google.com/github/a-coders-guide-to-ai/lessons/blob/main/This%20is%20How%20to%20Improve%20an%20Imbalanced%20Dataset.ipynb#scrollTo=968MW8wNN10_
SMOTE：https://dzlab.github.io/dltips/en/more/smote/

**Comment by mitsu-h** [comment]
SMOTEは線形補完を利用してoversamplingするため、構造化データにしか使えないと思われます。今回のタスクだと厳しそうです
